Evs BinaryTree
11cfif/spsuace--homework3 pull request #3
Opened 2019-03-21 21:19 UTC by Lenaami

2019-03-22 06:37 UTC, 11cfif requested changes
1) Очень много пропущенных пробелов и много в целом ошибок форматирования
2) много где пропущены проверки на null в начале методов
3) очень много копипасты, вы в каждом методе так или иначе ищете узел а потом что то делаете, так почему вам не стало лень писать 10 раз одно и тоже?)

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +
нет проверки на key == null

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +            if (compareResult > 0){
пробел

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +        if (root == null){
пробел и правильное выравнивание потеряли

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +                    closestToKeyChild.parent.rightChild = closestToKeyChild.rightChild;
а эта ветка достижима?

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +            if (node.rightChild == null){
а если node == null? что будет?

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +                node.parent = node.rightChild;
вы непереопределили детей родителя node
и в else тоже

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +                node.parent = node.rightChild;
у вас ветки почти полностью совпадают, зачем делить на null и не null если 90% кода совпадает. Почему не сделать разделение только на 10% кода и таким образом уменьшить копипасту?

2019-03-22 06:37 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +        Node parent;
приватные поля 
Устал уже повторять :(

2019-03-23 13:02 UTC, Lenaami commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +                    closestToKeyChild.parent.rightChild = closestToKeyChild.rightChild;
да, если у closestToKeyChild изначально не было leftChild

2019-03-24 07:24 UTC, 11cfif requested changes
одна ошибка осталась

2019-03-24 07:24 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +            closestToKeyChild.parent.rightChild = closestToKeyChild.rightChild;
Допустим у нас такая цепочка g <-> p <-> c, при удалении p вы сделали только такое g -> c, но обратную стрелочку не присвоили
->  связь ребенок
<- связь родитель

2019-03-24 07:24 UTC, 11cfif commented on src/main/java/ru/spsuace/homework3/collections/BinaryTree.java
> +    private Node findElement(K key) {
Хорошее решение, перегрузить метод с часто используемыми параметрами

2019-03-24 16:54 UTC, closed without merging